# Generated by Django 4.2 on 2023-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleData',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50)),
                ('hotel_name', models.CharField(max_length=200)),
                ('num_reviews', models.IntegerField()),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('address', models.CharField(max_length=200)),
                ('other_data', models.TextField()),
                ('is_mmt', models.IntegerField()),
                ('is_booking', models.IntegerField()),
                ('is_jd', models.IntegerField()),
                ('is_agoda', models.IntegerField()),
                ('is_cleartrip', models.IntegerField()),
                ('is_goibibo', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'google_data',
            },
        ),
        migrations.CreateModel(
            name='PincodesTable',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pincodes_table',
            },
        ),
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('time_of_query', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'request_table',
            },
        ),
        migrations.CreateModel(
            name='ScapeHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('hotel_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('other_data', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'scape_hotels',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('ph', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
