# Generated by Django 4.2 on 2023-04-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
